Upgrade plugin to omv version 6
seb36273/openmediavault-ldap pull request #7
Opened 2023-06-30 13:50 UTC by lucapiccio

Added compatibility with OMV6

Patched for ID and Machines mapping and new web interface

2023-07-02 07:04 UTC, seb36273 commented
Thank you for your contribution. I will review your code suggestion.

2023-07-02 07:31 UTC, seb36273 requested changes
Please can you make the changes? First I have to test your code suggestion. Many thanks!

2023-07-02 07:31 UTC, seb36273 commented on openmediavault-ldap_6.3.4_all.deb
@lucapiccio Can we remove this binary file? Maybe it is better if we create a Github pipeline for the release. I can take care of that later.

2023-07-02 07:31 UTC, seb36273 commented on openmediavault-ldap_6.3.4_all.deb
BTW How did you create this *.deb package? Did you use `dpkg-buildpackage -uc -us` inside source directory?

2023-07-02 07:31 UTC, seb36273 commented on README.md
> +git clone https://github.com/lucapiccio/openmediavault-ldap.git
We should not include this instruction. It depends on the repository and the user preferences.

2023-07-02 07:31 UTC, seb36273 commented on README.md
> +* Openmediavault 6.3.5-2 (Usul) with running SAMBA service
The name of OMV 6 is Shaitan, not Usul.

2023-07-02 08:44 UTC, lucapiccio commented on openmediavault-ldap_6.3.4_all.deb
Yes you have to delete the binary file, also it not is updated with last code update.

2023-07-02 08:49 UTC, lucapiccio commented
I've done the asked modification.

2023-07-02 08:51 UTC, lucapiccio commented
I suggest to create Release with a zip and deb file in assets of release version, it could be usefull for newbie users

2024-10-05 01:39 UTC, PlayerSchark commented
bump

2024-11-22 18:58 UTC, MassiPi commented
what happened to this?
anyone tried also with omv7?

2024-12-24 11:02 UTC, support4it commented
didnt work on my 6.9.16-1 (Shaitan), package compiled ok but after installation there is no menu in omv gui

2025-03-29 09:15 UTC, seb36273 commented
> what happened to this? anyone tried also with omv7?

I am just working on it. Please give me some time.

2025-03-29 21:55 UTC, seb36273 commented
> didnt work on my 6.9.16-1 (Shaitan), package compiled ok but after installation there is no menu in omv gui

@support4it I just updated the code (see https://github.com/seb36273/openmediavault-ldap/commit/f032c7757c30058f37f2a7a83861f13cc668e727) and merged changes in https://github.com/seb36273/openmediavault-ldap/commit/f032c7757c30058f37f2a7a83861f13cc668e727. I have successfully tested the debian package. The package is displayed in the new webgui of OpenMediaVault 6.9.16-1 without errors.

2025-03-29 22:00 UTC, seb36273 commented
@lucapiccio I fixed some issues in your code and merged the changes in https://github.com/seb36273/openmediavault-ldap/pull/11. Want to close this pull request. Many thanks for your contribution.

2025-03-29 22:00 UTC, closed without merging